; File: OT_01.mac
; Tests:  Trace file generation

.RADIX 10

.PSECT ABS

.=.+100
VAL1:     .WORD   5

.=.+98
VAL2:     .WORD   6

.PSECT REL

START:
          MOV   #100, R0
          MOV   #200, R1
          MOV   #1, R2
          MOV   #1, R3
          ADD   VAL1, R2
          ADD   VAL2, R3
          MOV   R2, @R0
          MOV   R3, @R1
          MOV   VAL1, R4
          MOV   VAL2, R5
          HALT

