; File: AM_08.mac
; Tests: Indexed deferred addressing

.RADIX 10
.PSECT ABS

.=.+100
        .WORD 20
        .WORD 30
        .WORD 40

.=.+94
        .WORD 100
        .WORD 102
        .WORD 104

.=.+94
        .WORD 50

.=.+98               ;location 400
        .WORD 300

.PSECT REL

START:
        MOV   #202, R0
        MOV   #398, R5
        MOV   @-2(R0), R2
        MOV   @0(R0), R3
        MOV   @2(R0), R4
        MOV   R4, @2(R5)  ;store R4 at address stored in 400 (address 300)
        MOV   @2(R5), R1
        CCC
        HALT

