; File: DO_04.mac
; Tests: Double operand bit clear instruction

.RADIX 10

L9:
        MOV   #3, R5
        HALT


L2:
        BCS   L9
        BVS   L9
        MOV   #3, R0
        HALT

L1:     
        BMI   L9
        BIC   R2, R1
        BMI   L2
        HALT

START:
        MOV   #-4, R1
        MOV   #1, R2
        MOV   #2, R3
        MOV   #1, R4
        BIC   R2, R3
        BEQ   L9
        BIC   R2, R4
        BEQ   L1
        HALT

