; File: SO_06.mac
; Tests: Add carry

.RADIX 10

L9:
        MOV     #5, R5
        HALT

L4:
        MOV     #3, R3
        HALT

L3:
        SEC   
        MOV     #-2, R1
        ADDC    R1
        BVS     L9
        BCS     L9
        BEQ     L9
        BMI     L4
        HALT

L2:
        SEC
        MOV     #-32768, R1
        ADDC    R1
        BVS     L9
        BCS     L3
        HALT

L1:
        SEC
        MOV     #32767, R1
        ADDC    R1
        BVS     L2
        HALT
        
START:
        SEC
        MOV     #-1, R1
        ADDC    R1
        BVS     L9
        BCS     L9
        BMI     L9
        BEQ     L1
        HALT

