; File: SO_08.mac
; Tests: Test

.RADIX 10

L9:
        MOV     #5, R5
        HALT

L2:
        MOV     #2, R2
        HALT

L1:
        MOV     #-2, R1
        TST     R1
        BCS     L9
        BVS     L9
        BEQ     L9
        BMI     L1
        HALT
START:
        MOV     #0, R1
        TST     R1
        BCS     L9
        BVS     L9
        BMI     L9
        BEQ     L2
        HALT

