; File: SO_03.mac
; Tests: Increment

.RADIX 10

L9:
        MOV     #5, R5
        HALT

L3:
        MOV   #3, R0
        HALT

L2:
        MOV    #-2, R1
        INC    R1
        BVS    L9
        BCS    L9
        BEQ    L9
        BMI    L3
        HALT
        
L1:
        MOV    #32767, R1
        INC    R1
        BVS    L2
        HALT


START:
        CCC
        MOV     #-1, R1
        INC     R1
        BCS     L9
        BMI     L9
        BVS     L9
        BEQ     L1
        HALT

