; File: SO_05.mac
; Tests: Negation (2's complement)

.RADIX 10

L9:
        MOV     #5, R5
        HALT

L4:
        MOV     #-3, R1
        NEG     R1
        HALT

L3:
        MOV     #-32768, R1
        NEG     R1
        BVS     L4
        HALT

L2:
        BCC     L3
        HALT

L1:
        MOV     #0, R1
        NEG     R1
        BVS     L9
        BMI     L9
        BEQ     L2
        HALT

START:
        CCC
        MOV     #1, R1
        NEG     R1
        BCC     L9
        BVS     L9
        BEQ     L9
        BMI     L2
        HALT

