; File: SO_09.mac
; Tests: Rotate Right with C

.RADIX 10

L9:
        MOV     #5, R5
        HALT

L4:
        MOV     #4, R3
        HALT

L3:
        MOV     #1, R1
        ROR     R1
        BCS     L4
        HALT

L2:
        MOV     #0, R1
        CCC
        ROR     R1
        BMI     L9
        BCS     L9
        BVS     L9
        BEQ     L3
        HALT

L1:
        ROR     R1
        BEQ     L9
        BMI     L9
        BVS     L2
        HALT

START:
        MOV     #2, R1
        SEC
        ROR     R1
        BCS     L9
        BEQ     L9
        BMI     L1
        HALT

