; File: CB_07.mac
; Tests: Branch if > 0
.PSECT A, REL

; L4 should not execute
L4:
        MOV   #4, R3
        HALT

; L3 should execute
L3:
        MOV   #3, R3
        HALT

; L2 should execute
L2:
        MOV   #2, R3
        CCC
        SEZ
        SEV
        BGT   L3
        HALT

; L1 should execute
L1: 
        MOV   #1, R3
        CCC
        SEZ
        BGT   L2
        HALT

START:
        CCC
        BLT   L4
        SEN
        SEV
        BLT   L4
        CCC
        SEV
        BLT   L1
        HALT

