; File: CB_04.mac
; Tests: Branch if !< 0
.PSECT A, REL

; L3 should not execute
L3:
        MOV   #3, R3
        HALT

; L2 should execute
L2:
        MOV   #2, R3
        HALT

; L1 should execute
L1: 
        MOV   #1, R3
        SEV
        SEN
        BGE   L2
        HALT

START:
        CCC
        SEN   
        BGE   L3
        CLN
        SEV
        BGE   L3
        CLV   
        BGE   L1
        HALT

