; File: CB_11.mac
; Tests: Branch if < | ==


; L4 should not execute
L4:
        MOV   #4, R3
        HALT

; L3 should execute
L3:
        MOV   #3, R3
        HALT

; L2 should execute
L2:
        MOV   #2, R3
        SEC
        BLOS  L3
        HALT

; L1 should execute
L1:
        MOV   #1, R3
        CLC
        SEZ
        BLOS  L2
        HALT

START:
        CCC
        BLOS  L2
        SEC
        BLOS  L1
        HALT

